using System.Globalization;
using System.Security.Cryptography;
using System.Text;

namespace FrameLink.Tests;

/// <summary>
/// Whether the committed <c>wwwroot</c> is the output of the committed <c>gui/</c> sources.
/// </summary>
/// <remarks>
/// <para>
/// <c>wwwroot</c> is a build artifact that is deliberately committed: §3.1 serves the Svelte
/// output with <c>UseStaticFiles()</c> out of one container, and §2.1's "no supplemental
/// program files" rule means the bundle belongs inside the image rather than beside it. A
/// committed artifact rots. The first time somebody edits a <c>.svelte</c> file and forgets to
/// rebuild, the repository serves last week's console — and nothing about that looks wrong.
/// No error, no log line, no failing request.
/// </para>
/// <para>
/// <b>This is the loud part.</b> <c>FrameLink.Control.csproj</c> rebuilds the GUI whenever a
/// source moves, but only where Node exists, and it deliberately treats a missing toolchain as
/// a warning rather than a build break. So the build cannot be the gate. This can: it re-hashes
/// every path named in <c>gui-build.stamp</c> and needs nothing but the repository, which means
/// it gives the same verdict on a fresh clone, in CI, and on a machine with no npm at all.
/// </para>
/// <para>
/// If this test is red, run <c>dotnet build src/FrameLink.Control</c> (or <c>npm run build</c>
/// in <c>gui/</c>) and commit what changes.
/// </para>
/// </remarks>
public sealed class GuiFreshnessTests
{
    /// <summary>Where a stamp line's hash ends and its path begins: 64 hex digits, two spaces.</summary>
    private const int PathOffset = 66;

    [Fact]
    public void The_committed_bundle_is_the_output_of_the_committed_sources()
    {
        var project = Path.Combine(RepositoryRoot(), "src", "FrameLink.Control");
        var stampPath = Path.Combine(project, "gui-build.stamp");

        Assert.True(
            File.Exists(stampPath),
            $"{stampPath} is missing. It is generated by the FrameLinkBuildGui target and is what "
            + "makes a stale GUI bundle visible; without it nothing checks the committed wwwroot.");

        var recorded = ReadStamp(stampPath);
        Assert.NotEmpty(recorded);

        var wrong = new List<string>();

        foreach (var (relativePath, expected) in recorded)
        {
            var full = Path.Combine(project, relativePath.Replace('/', Path.DirectorySeparatorChar));
            if (!File.Exists(full))
            {
                wrong.Add($"  missing   {relativePath}");
                continue;
            }

            var actual = Sha256Of(full);
            if (!string.Equals(actual, expected, StringComparison.Ordinal))
            {
                wrong.Add($"  changed   {relativePath}");
            }
        }

        // The other direction matters just as much. A new component that was compiled into the
        // bundle but never recorded, or a chunk left behind by an older build that
        // `adapter-static` no longer emits, are both "the stamp does not describe this tree".
        foreach (var relativePath in LiveFiles(project))
        {
            if (!recorded.ContainsKey(relativePath))
            {
                wrong.Add($"  unrecorded {relativePath}");
            }
        }

        Assert.True(
            wrong.Count == 0,
            "The Fleet Manager GUI bundle does not match its sources.\n\n"
            + string.Join('\n', wrong)
            + "\n\nRun `dotnet build src/FrameLink.Control` (or `npm run build` in "
            + "src/FrameLink.Control/gui) and commit wwwroot and gui-build.stamp together.");
    }

    [Fact]
    public void The_bundle_names_no_content_this_container_does_not_serve()
    {
        // §1.2 principle 1: self-hosting with no dependency on infrastructure this project
        // operates. A CDN reference in the bundle would make somebody else's fleet console
        // depend on a third party being up, and would do it invisibly — the console works
        // perfectly on the developer's machine, where the CDN is reachable.
        var wwwroot = Path.Combine(RepositoryRoot(), "src", "FrameLink.Control", "wwwroot");
        var offenders = new List<string>();

        foreach (var file in Directory.EnumerateFiles(wwwroot, "*", SearchOption.AllDirectories))
        {
            if (Path.GetExtension(file) is not (".html" or ".js" or ".css" or ".json"))
            {
                continue;
            }

            var text = File.ReadAllText(file);
            foreach (var host in KnownContentDelivery)
            {
                if (text.Contains(host, StringComparison.OrdinalIgnoreCase))
                {
                    offenders.Add($"  {Path.GetRelativePath(wwwroot, file)} references {host}");
                }
            }
        }

        Assert.True(
            offenders.Count == 0,
            "The GUI bundle reaches outside the container:\n" + string.Join('\n', offenders));
    }

    /// <summary>Hosts a self-hosted console must never need.</summary>
    private static readonly string[] KnownContentDelivery =
    [
        "cdn.jsdelivr.net",
        "unpkg.com",
        "cdnjs.cloudflare.com",
        "fonts.googleapis.com",
        "fonts.gstatic.com",
        "ajax.googleapis.com",
        "esm.sh",
    ];

    private static Dictionary<string, string> ReadStamp(string path)
    {
        var recorded = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var line in File.ReadLines(path))
        {
            if (line.Length <= PathOffset || line.StartsWith('#'))
            {
                continue;
            }

            recorded[line[PathOffset..]] = line[..64];
        }

        return recorded;
    }

    /// <summary>Every file the stamp is supposed to describe, as it is on disk right now.</summary>
    private static IEnumerable<string> LiveFiles(string project)
    {
        foreach (var file in Directory.EnumerateFiles(
            Path.Combine(project, "wwwroot"), "*", SearchOption.AllDirectories))
        {
            yield return Relative(project, file);
        }

        foreach (var directory in (string[])["src", "static", "tools"])
        {
            var full = Path.Combine(project, "gui", directory);
            if (!Directory.Exists(full))
            {
                continue;
            }

            foreach (var file in Directory.EnumerateFiles(full, "*", SearchOption.AllDirectories))
            {
                yield return Relative(project, file);
            }
        }
    }

    private static string Relative(string project, string file) =>
        Path.GetRelativePath(project, file).Replace('\\', '/');

    private static string Sha256Of(string path)
    {
        using var stream = File.OpenRead(path);
        var hash = SHA256.HashData(stream);

        var hex = new StringBuilder(hash.Length * 2);
        foreach (var b in hash)
        {
            hex.Append(b.ToString("x2", CultureInfo.InvariantCulture));
        }

        return hex.ToString();
    }

    /// <summary>Walks up from the test binary to the directory holding the solution.</summary>
    internal static string RepositoryRoot()
    {
        var probe = new DirectoryInfo(AppContext.BaseDirectory);
        for (var depth = 0; depth < 10 && probe is not null; depth++, probe = probe.Parent)
        {
            if (File.Exists(Path.Combine(probe.FullName, "FrameLink.slnx")))
            {
                return probe.FullName;
            }
        }

        throw new DirectoryNotFoundException(
            $"No FrameLink.slnx above {AppContext.BaseDirectory}; this test reads the repository, not the build output.");
    }
}
