using System.Globalization;
using System.Security.Cryptography;
using System.Text;

namespace FrameLink.Tests;

/// <summary>
/// Whether the committed <c>wwwroot</c> is the output of the committed <c>gui/</c> sources.
/// </summary>
/// <remarks>
/// <para>
/// <c>wwwroot</c> is a build artifact that is deliberately committed: §3.1 serves the Svelte
/// output with <c>UseStaticFiles()</c> out of one container, and §2.1's "no supplemental
/// program files" rule means the bundle belongs inside the image rather than beside it. A
/// committed artifact rots. The first time somebody edits a <c>.svelte</c> file and forgets to
/// rebuild, the repository serves last week's console — and nothing about that looks wrong.
/// No error, no log line, no failing request.
/// </para>
/// <para>
/// <b>This is the loud part.</b> <c>FrameLink.Control.csproj</c> rebuilds the GUI whenever a
/// source moves, but only where Node exists, and it deliberately treats a missing toolchain as
/// a warning rather than a build break. So the build cannot be the gate. This can: it re-hashes
/// every path named in <c>gui-build.stamp</c> and needs nothing but the repository, which means
/// it gives the same verdict on a fresh clone, in CI, and on a machine with no npm at all.
/// It hashes normalised content rather than raw bytes (see <see cref="Sha256OfContent"/>), so
/// that verdict is the same whether the checkout landed CRLF or LF — which it was not, until
/// the three tests below were written to hold it there.
/// </para>
/// <para>
/// If this test is red, run <c>dotnet build src/FrameLink.Control</c> (or <c>npm run build</c>
/// in <c>gui/</c>) and commit what changes.
/// </para>
/// </remarks>
public sealed class GuiFreshnessTests
{
    /// <summary>Where a stamp line's hash ends and its path begins: 64 hex digits, two spaces.</summary>
    private const int PathOffset = 66;

    /// <summary>How many leading bytes decide "is this text?" — git's own binary heuristic.</summary>
    private const int BinarySniffLength = 8000;

    [Fact]
    public void The_committed_bundle_is_the_output_of_the_committed_sources()
    {
        var project = Path.Combine(RepositoryRoot(), "src", "FrameLink.Control");
        var stampPath = Path.Combine(project, "gui-build.stamp");

        Assert.True(
            File.Exists(stampPath),
            $"{stampPath} is missing. It is generated by the FrameLinkBuildGui target and is what "
            + "makes a stale GUI bundle visible; without it nothing checks the committed wwwroot.");

        var recorded = ReadStamp(stampPath);
        Assert.NotEmpty(recorded);

        var wrong = new List<string>();

        foreach (var (relativePath, expected) in recorded)
        {
            var full = Path.Combine(project, relativePath.Replace('/', Path.DirectorySeparatorChar));
            if (!File.Exists(full))
            {
                wrong.Add($"  missing   {relativePath}");
                continue;
            }

            var actual = Sha256Of(full);
            if (!string.Equals(actual, expected, StringComparison.Ordinal))
            {
                wrong.Add($"  changed   {relativePath}");
            }
        }

        // The other direction matters just as much. A new component that was compiled into the
        // bundle but never recorded, or a chunk left behind by an older build that
        // `adapter-static` no longer emits, are both "the stamp does not describe this tree".
        foreach (var relativePath in LiveFiles(project))
        {
            if (!recorded.ContainsKey(relativePath))
            {
                wrong.Add($"  unrecorded {relativePath}");
            }
        }

        Assert.True(
            wrong.Count == 0,
            "The Fleet Manager GUI bundle does not match its sources.\n\n"
            + string.Join('\n', wrong)
            + "\n\nRun `dotnet build src/FrameLink.Control` (or `npm run build` in "
            + "src/FrameLink.Control/gui) and commit wwwroot and gui-build.stamp together.");
    }

    [Fact]
    public void The_bundle_names_no_content_this_container_does_not_serve()
    {
        // §1.2 principle 1: self-hosting with no dependency on infrastructure this project
        // operates. A CDN reference in the bundle would make somebody else's fleet console
        // depend on a third party being up, and would do it invisibly — the console works
        // perfectly on the developer's machine, where the CDN is reachable.
        var wwwroot = Path.Combine(RepositoryRoot(), "src", "FrameLink.Control", "wwwroot");
        var offenders = new List<string>();

        foreach (var file in Directory.EnumerateFiles(wwwroot, "*", SearchOption.AllDirectories))
        {
            if (Path.GetExtension(file) is not (".html" or ".js" or ".css" or ".json"))
            {
                continue;
            }

            var text = File.ReadAllText(file);
            foreach (var host in KnownContentDelivery)
            {
                if (text.Contains(host, StringComparison.OrdinalIgnoreCase))
                {
                    offenders.Add($"  {Path.GetRelativePath(wwwroot, file)} references {host}");
                }
            }
        }

        Assert.True(
            offenders.Count == 0,
            "The GUI bundle reaches outside the container:\n" + string.Join('\n', offenders));
    }

    [Fact]
    public void A_text_file_hashes_the_same_whether_the_checkout_is_CRLF_or_LF()
    {
        // The whole point. Hashing raw bytes made the stamp a fact about one person's disk: a
        // GUI source was committed with a CRLF hash, so the check was green on the machine that
        // built the bundle and red everywhere else, for a bundle that was perfectly current.
        var lf = Encoding.UTF8.GetBytes("<script>\n\tlet ready = false;\n</script>\n");
        var crlf = Encoding.UTF8.GetBytes("<script>\r\n\tlet ready = false;\r\n</script>\r\n");

        Assert.NotEqual(lf.Length, crlf.Length);
        Assert.Equal(Sha256OfContent(lf), Sha256OfContent(crlf));
    }

    [Fact]
    public void A_lone_carriage_return_is_content_and_survives()
    {
        // git strips CR only where it precedes LF. Matching that exactly is what makes the bytes
        // hashed here the bytes git stores, rather than merely close to them.
        var loneCarriageReturn = Encoding.UTF8.GetBytes("one\rtwo\n");
        var collapsed = Encoding.UTF8.GetBytes("onetwo\n");

        Assert.NotEqual(Sha256OfContent(loneCarriageReturn), Sha256OfContent(collapsed));
    }

    [Fact]
    public void A_binary_file_is_hashed_byte_for_byte()
    {
        // Not hypothetical: wwwroot/_app/immutable/assets/inter-latin-ext-wght-normal.DO1Apj_S.woff2
        // contains the byte pair CR LF. Normalising a font would throw away a difference the stamp
        // exists to see, so the NUL sniff that keeps binaries raw is load-bearing.
        byte[] carriageReturnInside = [0x77, 0x4f, 0x46, 0x32, 0x00, 0x0d, 0x0a, 0x01];
        byte[] withoutIt = [0x77, 0x4f, 0x46, 0x32, 0x00, 0x0a, 0x01];

        Assert.NotEqual(Sha256OfContent(carriageReturnInside), Sha256OfContent(withoutIt));
    }

    /// <summary>Hosts a self-hosted console must never need.</summary>
    private static readonly string[] KnownContentDelivery =
    [
        "cdn.jsdelivr.net",
        "unpkg.com",
        "cdnjs.cloudflare.com",
        "fonts.googleapis.com",
        "fonts.gstatic.com",
        "ajax.googleapis.com",
        "esm.sh",
    ];

    private static Dictionary<string, string> ReadStamp(string path)
    {
        var recorded = new Dictionary<string, string>(StringComparer.Ordinal);

        foreach (var line in File.ReadLines(path))
        {
            if (line.Length <= PathOffset || line.StartsWith('#'))
            {
                continue;
            }

            recorded[line[PathOffset..]] = line[..64];
        }

        return recorded;
    }

    /// <summary>Every file the stamp is supposed to describe, as it is on disk right now.</summary>
    private static IEnumerable<string> LiveFiles(string project)
    {
        foreach (var file in Directory.EnumerateFiles(
            Path.Combine(project, "wwwroot"), "*", SearchOption.AllDirectories))
        {
            yield return Relative(project, file);
        }

        foreach (var directory in (string[])["src", "static", "tools"])
        {
            var full = Path.Combine(project, "gui", directory);
            if (!Directory.Exists(full))
            {
                continue;
            }

            foreach (var file in Directory.EnumerateFiles(full, "*", SearchOption.AllDirectories))
            {
                yield return Relative(project, file);
            }
        }
    }

    private static string Relative(string project, string file) =>
        Path.GetRelativePath(project, file).Replace('\\', '/');

    private static string Sha256Of(string path) => Sha256OfContent(File.ReadAllBytes(path));

    /// <summary>
    /// SHA-256 of a file's <em>content</em>, with the checkout's line-ending convention divided
    /// out of it.
    /// </summary>
    /// <remarks>
    /// <para>
    /// This used to hash the raw bytes, which quietly made the check ask a different question on
    /// every machine. A working tree holding CRLF — which is what any tool writing "native" line
    /// endings leaves behind, whatever <c>.gitattributes</c> asked for — hashes differently from
    /// the same file checked out LF, so <c>gui-build.stamp</c> was only ever valid for the one
    /// working tree that generated it. It passed for whoever ran the build and failed for
    /// everybody else, naming files they had never touched. That is indistinguishable from the
    /// stale bundle this test exists to catch, so hashing raw bytes was worse than merely noisy:
    /// it spent the check's credibility on an answer about the reader's disk.
    /// </para>
    /// <para>
    /// Stripping CR only where it precedes LF is not an approximation of git's rule, it is git's
    /// rule. So the bytes hashed here are the bytes git stores in the object database, and the
    /// stamp is a statement about the committed content rather than about one checkout.
    /// </para>
    /// <para>
    /// Binary files are hashed byte for byte, decided by git's own heuristic: a NUL in the first
    /// <see cref="BinarySniffLength"/> bytes. That guard is load-bearing rather than decorative —
    /// one of the three woff2 fonts in <c>wwwroot</c> really does contain the byte pair CR LF, and
    /// normalising a font would discard a difference the stamp exists to see.
    /// </para>
    /// </remarks>
    internal static string Sha256OfContent(ReadOnlySpan<byte> raw)
    {
        ReadOnlySpan<byte> content = LooksBinary(raw) ? raw : WithoutCarriageReturns(raw);
        var hash = SHA256.HashData(content);

        var hex = new StringBuilder(hash.Length * 2);
        foreach (var b in hash)
        {
            hex.Append(b.ToString("x2", CultureInfo.InvariantCulture));
        }

        return hex.ToString();
    }

    /// <summary>git's binary test: a NUL byte anywhere in the leading sniff window.</summary>
    private static bool LooksBinary(ReadOnlySpan<byte> bytes) =>
        bytes[..Math.Min(bytes.Length, BinarySniffLength)].IndexOf((byte)0) >= 0;

    /// <summary>CRLF to LF, leaving a lone CR alone — exactly what git's <c>text</c> filter does.</summary>
    private static byte[] WithoutCarriageReturns(ReadOnlySpan<byte> bytes)
    {
        var kept = new byte[bytes.Length];
        var length = 0;

        for (var i = 0; i < bytes.Length; i++)
        {
            if (bytes[i] == (byte)'\r' && i + 1 < bytes.Length && bytes[i + 1] == (byte)'\n')
            {
                continue;
            }

            kept[length++] = bytes[i];
        }

        return kept[..length];
    }

    /// <summary>Walks up from the test binary to the directory holding the solution.</summary>
    internal static string RepositoryRoot()
    {
        var probe = new DirectoryInfo(AppContext.BaseDirectory);
        for (var depth = 0; depth < 10 && probe is not null; depth++, probe = probe.Parent)
        {
            if (File.Exists(Path.Combine(probe.FullName, "FrameLink.slnx")))
            {
                return probe.FullName;
            }
        }

        throw new DirectoryNotFoundException(
            $"No FrameLink.slnx above {AppContext.BaseDirectory}; this test reads the repository, not the build output.");
    }
}
