#!/usr/bin/env node
/**
 * Writes `../../gui-build.stamp`: a SHA-256 manifest of everything the GUI build reads and
 * everything it produces.
 *
 * The stamp exists to answer one question loudly — **is the committed `wwwroot` the output of
 * the committed `gui/` sources?** `wwwroot` is a build artifact that is deliberately committed
 * (§3.1: one container, no loose asset trees beside the binary), which means it can silently
 * fall behind the source the first time somebody edits a `.svelte` file and forgets to rebuild.
 * Nothing about a stale bundle looks broken; it just serves last week's console.
 *
 * `GuiFreshnessTests` in the C# suite reads this file back and re-hashes every path in it, so
 * a stale or hand-edited `wwwroot` is a red test rather than a discovery in production.
 *
 * The format is deliberately a flat list rather than one combined hash:
 *
 *   #  comment lines
 *   <sha256-hex>  <path relative to src/FrameLink.Control, forward slashes>
 *
 * Two reasons. There is no "combine the hashes" algorithm to reimplement identically on the C#
 * side — only `sha256(file bytes)`, which is a primitive and not a choice. And `git diff` on
 * this file names exactly which GUI files a commit touched, which is the review question
 * anyway.
 *
 * Raw bytes are hashed with no line-ending normalisation, which is safe because
 * `.gitattributes` pins `* text=auto eol=lf`: the working tree is LF on every OS, so the bytes
 * on disk are the bytes in history.
 */

import { createHash } from 'node:crypto';
import { readFile, readdir, stat, writeFile } from 'node:fs/promises';
import { join, posix, relative, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const GUI = resolve(fileURLToPath(new URL('..', import.meta.url)));
const PROJECT = resolve(GUI, '..');
const STAMP = join(PROJECT, 'gui-build.stamp');

/**
 * What the build reads. Everything else under `gui/` — `mock/`, `.vscode/`, `node_modules/`,
 * `.svelte-kit/` — is deliberately absent: a file that cannot change the output must not be
 * able to fail the freshness check, or the check trains people to regenerate it reflexively.
 */
const SOURCE_DIRECTORIES = ['src', 'static', 'tools'];
const SOURCE_FILES = ['package.json', 'package-lock.json', 'vite.config.ts', 'tsconfig.json', '.npmrc'];

/** What the build produces, and what `UseStaticFiles()` serves. */
const OUTPUT_DIRECTORY = resolve(PROJECT, 'wwwroot');

async function walk(directory) {
	const found = [];
	let entries;
	try {
		entries = await readdir(directory, { withFileTypes: true });
	} catch {
		return found;
	}

	for (const entry of entries) {
		const full = join(directory, entry.name);
		if (entry.isDirectory()) {
			found.push(...(await walk(full)));
		} else if (entry.isFile()) {
			found.push(full);
		}
	}
	return found;
}

async function hashOf(path) {
	return createHash('sha256')
		.update(await readFile(path))
		.digest('hex');
}

const files = [];
for (const directory of SOURCE_DIRECTORIES) {
	files.push(...(await walk(join(GUI, directory))));
}
for (const file of SOURCE_FILES) {
	const full = join(GUI, file);
	try {
		if ((await stat(full)).isFile()) files.push(full);
	} catch {
		// A missing optional file (.npmrc) is simply absent from the manifest, and its absence
		// is itself recorded — the C# side compares the whole list, not a subset.
	}
}
files.push(...(await walk(OUTPUT_DIRECTORY)));

const lines = await Promise.all(
	files.map(async (file) => `${await hashOf(file)}  ${posix.normalize(relative(PROJECT, file).split(/[\\/]/).join('/'))}`)
);

lines.sort((a, b) => (a.slice(66) < b.slice(66) ? -1 : a.slice(66) > b.slice(66) ? 1 : 0));

await writeFile(
	STAMP,
	[
		'# Generated by gui/tools/stamp.mjs. Do not edit by hand.',
		'#',
		'# SHA-256 of every file the Fleet Manager GUI build reads, and of every file it wrote',
		'# into wwwroot. Regenerated by the FrameLinkBuildGui target in FrameLink.Control.csproj',
		'# and verified by GuiFreshnessTests, which is what turns a stale committed bundle from',
		'# a silent wrong-console-in-production into a red test.',
		'#',
		'# To refresh it: dotnet build src/FrameLink.Control  (or: npm run build in gui/)',
		'',
		...lines,
		''
	].join('\n'),
	'utf8'
);

console.log(`gui-build.stamp: ${lines.length} files`);
